language: objective-c

before_script:
  - bin/ci/travis/instruments-auth.sh

script:
  - bin/ci/travis/run.sh

notifications:
  email:
    recipients:
      - joshuajmoody@gmail.com
      - chris.fuentes@xamarin.com
      - villars.gimm@xamarin.com
    on_success: change
    on_failure: always

