variables:
  # When Agent.JobName matches this value (and the git ref is a tag), then
  # built artifacts will be published to Azure Blob Storage.
- name: "AzurePublishWhen"
  value: "Monterey-Xcode-13.3.1"
- name: "RunTestCloudTestsWhen"
  value: "Monterey-Xcode-13.3.1"
- name: EOCompliance-Mac
  value: true
trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - master
pr:
  branches:
    include:
    - master
schedules:
- cron: "0 23 * * Mon-Fri"
  displayName: Nightly build
  branches:
    include:
    - master
  always: true

jobs:

- job:
  strategy:
    matrix:
      BigSur-Xcode-13.2:
        IMAGE_POOL: 'macOS-11'
        XCODE_VERSION: '13.2'
      Monterey-Xcode-13.3.1:
        IMAGE_POOL: 'macOS-12'
        XCODE_VERSION: '13.3.1'
  timeoutInMinutes: 180
  pool:
    vmImage: $(IMAGE_POOL)
  variables:
  - group: XTCRunTimeArtifactsCI

  steps:

  - script: |
      set -e
      sudo xcode-select --switch "/Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer"
      echo "Xcode version: $(xcrun xcodebuild -version)"
      echo "Xcode path: $(xcrun -f xcodebuild)"
      echo "Xcode select path: $(xcode-select --print-path)"
    displayName: "Select Xcode $(XCODE_VERSION)"

  - script: |
      set -e
      ruby -v
      echo -e "install: --no-document --env-shebang\nupdate:  --no-document --env-shebang" > ~/.gemrc
      gem install bundler -v 2.3.18
      bundle _2.3.18_ install
      bundle install
    displayName: "Prepare Ruby Environment"

  - script: |
      set -e
      [ -d "calabash-codesign" ] && rm -rf calabash-codesign
      git clone https://$(CalabashKeychainGitHubAccessToken)@github.com/xamarinhq/calabash-codesign.git
      calabash-codesign/apple/create-keychain.sh
    displayName: "Download and install keychain"

  - script: make app
    displayName: "Make app"

  - script: make ipa
    displayName: "Make ipa"

      #- script: bundle exec bin/ci/cucumber.rb
      #  displayName: "bin/ci/cucumber.rb"

  - script: |
      nuget restore $(Build.SourcesDirectory)/Permissions_UITest/Permissions_UITest/Permissions_UITest.sln
      msbuild $(Build.SourcesDirectory)/Permissions_UITest/Permissions_UITest/Permissions_UITest.csproj
    displayName: Build Permissions_UITest

    - script: bundle exec bin/ci/appcenter.rb
     env:
       APPCENTER_ACCESS_TOKEN: $(AppCenterAPITokenProd)
       SOURCE_DIRECTORY: $(Build.SourcesDirectory)
     displayName: Run Appcenter Test

  - task: Bash@3
    inputs:
      targetType: filePath
      filePath: "./bin/ci/az-publish.sh"
    env:
      AZURE_STORAGE_ACCOUNT: $(AzureStorageAccount)
      AZURE_STORAGE_KEY: $(AzureStorageKey)
      AZURE_STORAGE_CONNECTION_STRING: $(AzureStorageConnectionString)
      SOURCE_BRANCH: $(Build.SourceBranch)
    displayName: "Publish to Azure Blob Storage"
    condition: and(succeeded(), eq(variables['Agent.JobName'], variables['RunTestCloudTestsWhen']), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'IndividualCI'))

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      failTaskOnFailedTests: true
      testResultsFiles: 'reports/junit/**/*.xml'
    condition: always()
