<%

calabash_dir = File.expand_path(File.join(ENV["HOME"], ".calabash"))

devices = {}

device_list = ['iphone5S', 'iphone4S', 'iphone6', 'iphone6plus', 'ipadmini']

device_list.each do |device|
  dir = "#{calabash_dir}/devices/#{device}"
  ip = IO.read("#{dir}/ip") if File.exists?("#{dir}/ip")
  udid = IO.read("#{dir}/udid") if File.exists?("#{dir}/udid")
  ht = {:dir => dir,
        :ip => ip,
        :udid => udid}
  devices[device.to_sym] = ht
end

%>

verbose: DEBUG=1
formatter: -f pretty

# Launch on default simulator.
simulator_vars: APP="./Products/app/Permissions.app"
simulator_tags: --tags 'not @device_only' --tags 'not @device'
default:        -p simulator_vars -p simulator_tags -p formatter

# Launch on device.
device_tags:  --tags 'not @simulator_only' --tags 'not @simulator'
device:       -p device_tags -p formatter APP=sh.calaba.Permissions -p formatter

iphone5S:    -p device DEVICE_TARGET=<%= devices[:iphone5S][:udid] %>    DEVICE_ENDPOINT=<%= devices[:iphone5S][:ip] %>
iphone4S:    -p device DEVICE_TARGET=<%= devices[:iphone4S][:udid] %>    DEVICE_ENDPOINT=<%= devices[:iphone4S][:ip] %>
iphone6:     -p device DEVICE_TARGET=<%= devices[:iphone6][:udid] %>     DEVICE_ENDPOINT=<%= devices[:iphone6][:ip] %>
iphone6plus: -p device DEVICE_TARGET=<%= devices[:iphone6plus][:udid] %> DEVICE_ENDPOINT=<%= devices[:iphone6plus][:ip] %>
ipadmini:    -p device DEVICE_TARGET=<%= devices[:ipadmini][:udid] %>    DEVICE_ENDPOINT=<%= devices[:ipadmini][:ip] %>

# Joshua's devices
neptune: -p iphone4S
uranus:  -p iphone5S
hat:     -p iphone6
denis:   -p iphone6plus
pegasi:  -p ipadmini

